- .github/workflows/secureliCI.yml
- Dockerfile_homebrew
This is an experiment to see if adding a specific token to the checkout makes it possible to push back with current permissions.
> chore: adding specific token to code checkout

- .github/workflows/secureliCI.yml
- templates/formula.txt
* Adds release creation to deployment code
* Updating formula template to remove custom download strategy
> chore: modify deployment code

- pyproject.toml
creates a commit message for semver allowing us to skip ci on tag pushes.
> chore: enhance semver commit message

- .github/workflows/pr_lint.yml
Adding PR with bad title again. This seems to be reliably failing bad titles. It's less reliable if the title is good and then changed to something bad but hopefully no one does that.
> chore: add pr linting

- .github/workflows/secureliCI.yml
- scripts/get-current-branch.sh
changes the branch name checker to align with github issue titles
> chore: secureli-82 update branch linting

- .github/dependabot.yml
this adds a dependabot config file that has it scanning for updates to the pip libraries and the github-actions external actions. I'm not sure how this will play out so we'll have to watch it for a while.
> chore: secureli 74 dependabot contributions

- secureli/abstractions/pre_commit.py
- tests/services/test_git_ignore.py
recent library upgrades required two files to be relinted
> chore: apply lint

- .github/workflows/secureliCI.yml
- secureli/abstractions/pre_commit.py
- secureli/resources/files/configs/typescript.config.yaml
- secureli/resources/files/javascript-pre-commit.yaml
- secureli/resources/files/typescript-pre-commit.yaml
Add Eslint + Prettier to pre-commit via typescript plugins.
> chore: Update TS pre-commit

- scripts/get-current-branch.sh
fix dependabot branch names getting hung up in validation
> chore: secureli 140 dependabot branch validation

- secureli/resources/files/swift-pre-commit.yaml
- secureli/services/language_support.py
- tests/repositories/test_settings_repository.py
Adds support for SwiftLinting and detect-secrets for Swift codebases.
> feat: #63 swift language support

- .github/workflows/secureliCI.yml
updates the `secureliCI` workflow to use the new GH App installation token instead of Sascha's PAT.
> feat: updates workflow to use gh app token

- .github/workflows/secureliCI.yml
- pyproject.toml
just looking for some semver feedback to see why it's not pushing new versions
> chore: adding verbosity to semver

- .github/workflows/secureliCI.yml
- pyproject.toml
> chore: feature/secureli 999 broken build

- CONTRIBUTING.md
Adding Sucha to the contributing.md
> chore: update contributing.md

- .github/workflows/secureliCI.yml
https://github.com/slalombuild/secureli/issues/185
> feat: swaps token for semantic release to github app token (#185)

- .github/workflows/secureliCI.yml
> chore: replaces all PAT uses with GH App token

- .github/workflows/build_and_test.yml
- .github/workflows/publish.yml
- Dockerfile_secureli
- pyproject.toml
- secureli/repositories/settings.py
Resolving string representation of enum for EchoLevel
Edited TOML file
> feat: Added Python 3.11 support

- .github/workflows/build_and_test.yml
- .github/workflows/publish.yml
- Dockerfile_secureli
- pyproject.toml
https://github.com/slalombuild/secureli/issues/318
> chore: Reverting python from 3.11 to 3.9

- scripts/get-secureli-dependencies.py
> chore: Issue 320 - remove six from exclude list

- scripts/get-secureli-dependencies.py
> fix: remove pre-commit from homebrew formula ignore list

- templates/formula.txt
> fix: Revert homebrew formula changes

- .github/workflows/build_and_test.yml
- .github/workflows/integration_testing.yml
secureli-394
This PR enables github caching for various build and testing steps
* Update .github/workflows/build_and_test.yml with caching options
* Update .github/workflows/integration_testing.yml with caching options
* No new tests
> feat: Feature/secureli 394 gh cache action

- CONTRIBUTING.md
- README.md
secureli-396
closes #396 
General updates and clean up to readme and contributing guides.
* Updated README.md
* Updated CONTRIBUTING.md
N/A
> chore: readme and contributing guide updates

- .github/workflows/integration_testing.yml
- Dockerfile_homebrew
- Dockerfile_pypi
- secureli/abstractions/pre_commit.py
- secureli/actions/action.py
- secureli/actions/scan.py
- secureli/main.py
- secureli/services/scanner.py
- tests/abstractions/test_pre_commit.py
- tests/application/test_main.py
- tests/end-to-end/test.bats
secureli-390
closes #390
Adding the ability to scan a subset of files/folders in a repo
* Added a new cli option to the `Scan` action: `--file, -f`
* This can be passed a file or folder as a value
* The option needs to be added multiple times in order to pass multiple files i.e. `--file file1 --file file2` (note: this is a behavior of Typer, which does not support an option having >1 values unless they are a fixed amount) 
* https://typer.tiangolo.com/tutorial/multiple-values/options-with-multiple-values/
* https://typer.tiangolo.com/tutorial/multiple-values/arguments-with-multiple-values/
* Passing an array of files to pre-commit to run hooks on
* Removing unused `yes` arg from scan since it is not used in any logic and is defaulted to `False` during a scan.
* Run scan with the file arg …
> feat: add file arg to scan in order to run hooks on specified files/paths

- secureli/actions/update.py
secureli-432
Improve UX by adding informational print to the console while update action is running.
* Added progress bar from Rich package to indicate that repos are updating
* All existing unit tests are passing
* Screenshot of progress bar:
> feat: add loading notification when updating

- CONTRIBUTING.md
> docs: update contributor list 

- secureli/modules/core/core_services/scanner.py
- secureli/modules/core/core_services/updater.py
- secureli/modules/observability/observability_services/logging.py
- secureli/modules/shared/models/logging.py
- secureli/modules/shared/models/scan.py
- secureli/modules/shared/models/update.py
- secureli/modules/shared/utilities.py
- tests/actions/test_action.py
- tests/actions/test_update_action.py
- tests/modules/core/test_scanner_service.py
secureli-453
Audited and updated core and observability modules
* Audited and updated core and observability modules
* No change or update to functionality, just re-organize code per audit.
* All existing unit tests pass
> chore: audited and updated core and observability modules
