slalombuild/secureli

- secureli/repositories/settings.py
#77 Bugfix for failing to write ignore rule to .secureli.yml when it does not exist yet
Note that this PR is for Github issue #77 and not Jira ticket STFT-077.  Branch was named as such to pass branch validation until branch validation has been updated.
Adds conditional logic so that saving the settings file does not attempt to modify the echo property if there is no echo property.
> fix: Resolves setting save failure on empty secureli.yaml

- poetry.lock
- pyproject.toml
- scripts/get-secureli-dependencies.py
Fixes - https://github.com/slalombuild/secureli/issues/80
Resolution
* Move pre-commit to being a required dependency. This should force the pip installation to pull that package down
* Updating the homebrew formula creation script to filter out packages that are needed for pip but not the homebrew formula
* Updating lock file to reflect pre-commit being moved to a dependency
> chore: Add pre-commit as dependency

- secureli/actions/action.py
Fixes Issue when running secureli init on an existing repo.  The log output indicates that the entire repo will be scanned for secrets but the default behavior is to call detect-secrets without the `--all-files` flag so that a baseline is created.
[#90 Running secureli init on existing repo does not appear to run full scan](https://github.com/slalombuild/secureli/issues/90)
> fix: detect-secrets-init-text

- secureli/actions/scan.py
- secureli/services/logging.py
- secureli/utilities/usage_stats.py
- tests/services/test_logging_service.py
- tests/utilities/test_usage_stats.py
Log format has been modified to
- failure.details change to just a list of failures, instead of the terminal type notation with the color and etc.
- adding total_failure_count
- adding failure_count_details for individual failure count
Log will look more or less like this (removing machine id, and other personal identification in the below sample)
```
{
"action": "SCAN",
"failure_count_details.black": 1,
"failure_count_details.detect_secrets": 2,
"failure.details": "[{\"repo\": \"https://github.com/Yelp/detect-secrets\", \"id\": \"detect-secrets\", \"file\": \"secureli/services/scanner.py\"}, {\"repo\": \"https://github.com/Yelp/detect-secrets\", \"id\": \"detect-secrets\", \"file\": \"secureli/services/logging.py\"}, {\"repo\": \"https://github.com/psf/black\", \"id\": \"black\", …
```
> chore: Clean Up Log Format to accomodate collecting usage stats metric for instrumentation purposes

- CONTRIBUTING.md
- Dockerfile_homebrew
- Dockerfile_pypi
- Dockerfile_secureli
- ca-certificates/.gitignore
This PR allows a contributor to put a Trusted Root Certificate Authority in the ca-certificates directory of this repo in order to allow access through a corporate proxy that sniffs SSL/TLS traffic.
> chore: Add CA Certificates capability to Dockerfiles

- secureli/resources/files/go-pre-commit.yaml
- secureli/services/language_support.py
- tests/actions/test_scan_action.py
Adding linter for Go Language, as well as pre commit hook and detect secret
Also fix unit tests due to environment variable issue.
Screenshot is showing golangci-lint caught an issue during secureli scanning
> chore: secureli-59 adding support to Go

- .pre-commit-config.yaml
- secureli/abstractions/pre_commit.py
- secureli/actions/action.py
- secureli/actions/build.py
- secureli/actions/initializer.py
- secureli/actions/scan.py
- secureli/actions/update.py
- secureli/main.py
- secureli/repositories/secureli_config.py
- secureli/services/language_support.py
- secureli/services/logging.py
- secureli/services/updater.py
- secureli/utilities/git_meta.py
- tests/abstractions/test_pre_commit.py
- tests/actions/test_action.py
- tests/actions/test_initializer_action.py
- tests/actions/test_update_action.py
- tests/application/test_main.py
- tests/repositories/test_secureli_config.py
- tests/services/test_language_support.py
- tests/services/test_logging_service.py
- tests/services/test_updater_service.py
- tests/utilities/test_git_meta.py
This will add the ability to the 3 commands `init` `scan` `update` with `--directory`
example:
`secureli scan -m all-files --directory ~/src/testrepo`
> feat: adding optional directory command for init, scan, and update

- secureli/abstractions/pre_commit.py
- secureli/actions/action.py
- secureli/actions/build.py
- secureli/actions/initializer.py
- secureli/actions/scan.py
- secureli/actions/update.py
- secureli/main.py
- secureli/repositories/secureli_config.py
- secureli/services/language_support.py
- secureli/services/logging.py
- secureli/services/updater.py
- secureli/utilities/git_meta.py
- tests/abstractions/test_pre_commit.py
- tests/actions/test_action.py
- tests/actions/test_initializer_action.py
- tests/actions/test_update_action.py
- tests/application/test_main.py
- tests/repositories/test_secureli_config.py
- tests/services/test_language_support.py
- tests/services/test_logging_service.py
- tests/services/test_updater_service.py
- tests/utilities/test_git_meta.py
Reverts slalombuild/secureli#147
> Revert "feat: adding optional directory command for init, scan, and update"

- .github/workflows/secureliCI.yml
- pyproject.toml
I think semver 8+ needs a pydantic version we aren't using. I don't know why we aren't getting better versioning errors but let's see what pinning to a 7.x version does for us.
> chore: reduce semver version

- secureli/services/logging.py
The logging failure function was given two new arguments that were intended to be optional, but they were accidentally made required. Existing calls providing two arguments were no longer compatible with the function, which now required four.
Failures during initialization or upgrade were causing crashes.
> fix: unintended breaking change with logging function

- .github/workflows/secureliCI.yml
The new version of semantic release separated the steps to create a new release and upload the release assets.  This should fix the issue with homebrew release.
https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html
> chore: Adds the step to upload to gh releases

- .github/workflows/publish.yml
adds needs block and if condition to run tests after other jobs complete
> chore: ensure tests run after other publish jobs finish

- secureli/main.py
- secureli/services/updater.py
https://github.com/slalombuild/secureli/issues/159
[Pre-commit does not support using a latest tag](https://pre-commit.com/#using-the-latest-version-for-a-repository), the only way to use latest is to update after install.
I tested these changes by updating the version I installed with brew re-initializing a test repo with javascript and python code. It looks like the fix I made to the update command could use a regression test, that line of code cannot run without a folder path argument.
> chore: Issue 159 - Using latest git hooks

- secureli/main.py
- tests/application/test_main.py
closes #170 
Adds option to display the current seCureLI version in the terminal using either `-v` or `--version`
> feat: add version option functionality

- CONTRIBUTING.md
- secureli/utilities/git_meta.py
- tests/utilities/test_git_meta.py
Resolves #261
The `configparser` module by default assumes that '%' characters indicate the presence of a variable and will try to parse a config value accordingly. Switching to "raw" mode prevents this behavior.
Manually tested by changing my `.git/config` file to set the origin URL to include `%20`, and was able to replicate the failure detailed in the ticket.
> fix: Correctly parsing %-encoded URLs from .git/config file

- secureli/abstractions/echo.py
- secureli/repositories/settings.py
- secureli/utilities/logging.py
- tests/abstractions/test_typer_echo.py
Implementing the following changes:
1. Add debug log level (colored cyan)
2. Make error messages print to stderr instead of stdout
3. include "[seCureLI] [\<log level\>] " prefix to messages
4. Update default log level from ERROR to WARN
5. Move log level enum to separate class and use more consistently
This is what output would look like now (with debug logging enabled):
Updated unit tests
> chore: Improve terminal output

- secureli/container.py
- secureli/resources/files/configs/javascript.config.yaml
- secureli/resources/files/configs/typescript.config.yaml
- secureli/services/language_config.py
- secureli/services/language_support.py
- tests/services/test_language_support.py
closes #344
Fixes issue where linter config files (i.e. .eslintrc.yaml) were not being created and also had generic file names. Files will now be created using the filename and config data contents specified in the specific yaml resources.
> fix: linter config file creation

- .pre-commit-config.yaml
- secureli/abstractions/pre_commit.py
- secureli/actions/scan.py
- secureli/main.py
- secureli/models/publish_results.py
- secureli/models/result.py
- secureli/services/logging.py
- secureli/utilities/usage_stats.py
- tests/actions/test_scan_action.py
- tests/utilities/test_usage_stats.py
Instead of only detecting scan vs commit scenarios, I added a CLI param to set when metrics should be published (`always`, `never`, or `on-fail`) and utilized that by setting the git pre-commit hook to `secureli scan --publish-results=always`.
One other notable change is that I added a `models/` directory. I think it would make sense to migrate various pydantic models & enums there in the future.
* Added a few unit tests
* Updated some existing unit tests
* Manual testing shows correct behavior
> feat: Only publish metrics on commit

- pyproject.toml
- scripts/get-secureli-dependencies.py
- secureli/resources/files/configs/javascript.config.yaml
- secureli/resources/files/configs/typescript.config.yaml
- secureli/resources/files/pre-commit/lint/javascript-pre-commit.yaml
- secureli/resources/files/pre-commit/lint/typescript-pre-commit.yaml
closes #337
- Replace the `eslint-google-config` settings with `eslint:recommended` for generated typescript and javascript eslint config files.
- Add missing module `identify` to homebrew formula
- Fix lint config issues
1. Fix mismatched file names in pre-commit file and config files
2. Create separate files for JavaScript and TypeScript
3. Add missing dependency for needed TypeScript pre-commit file
> chore: replace unsupported google eslint with eslint recommended

- scripts/get-secureli-dependencies.py
closes #368 
remove cfgv from exclude list so that it is added to homebrew formula
> fix: remove cfgv from homebrew exclude list

- .github/workflows/integration_testing.yml
closes #370 
updates and splits up init/scan secureli commands for homebrew mac os integration test. The test is currently failing due to the scan command not checking all files and expecting committed files.
> fix: Fix failing macos homebrew integration test

- poetry.lock
- pyproject.toml
By restricting the supported python range, we can fix `poetry shell && poetry install` to not attempt to install secureli on python 3.12.
I'm also hoping that once this gets released it will update the [PyPI listing](https://pypi.org/project/secureli/) to not include python 3.12 in the supported python versions.
I also moved up the `[build-system]` block to the top of `pyproject.toml`, since it's a top-level & required section.
```
% poetry env use 3.12
Using virtualenv: /Users/tyler.durkota/Library/Caches/pypoetry/virtualenvs/secureli-TKSW7H2l-py3.12
% poetry shell
Current Python version (3.12.1) is not allowed by the project (>= 3.9, < 3.12).
Please change python executable via the "env use" command.
```
> fix: Restrict to python 3.11 & lower in pyproject.toml

- .github/workflows/integration_testing.yml
closes #380 
Add removal of existing python 12 installation to macos homebrew integration test to avoid brew link issues.
> fix: update script to also remove python 12 during integration test install

- .github/workflows/integration_testing.yml
This PR has workflow changes to address expected homebrew dependency installation errors during integration testing
> fix: Feature/secureli 386 homebrew tests failing

- .github/workflows/build_and_test.yml
- .github/workflows/pr_lint.yml
- pyproject.toml
- tests/end-to-end/test.bats
secureli-128
Running BATS to validate e2e tests on every PR push. They seem to run pretty quickly so it shouldn't add much latency to the pipeline.
* BATS tests now run in the pipeline and print out verbose results (This work was done by @joe-stafford )
* Enabling `ci:` as a valid PR prefix, as it's supported by [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
* Fixed existing BATS tests & enabled them in the pipeline
> ci: Run BATS test in pipeline 

- pyproject.toml
secureli-250
Instead of completing the work that was originally planned for #250 (appending `-A` to our release version), we've opted to not do that but in the process of investigating I found that there was a minor typo in the `pyproject.toml` file that was preventing some of the options from getting picked up correctly.
* No new tests were added, but I performed manual testing with a local invocation of `pre-commit version`.
> fix: Fix semantic-release config

- .vscode/launch.json
- .vscode/settings.json
- secureli/main.py
secureli-175
When running `secureli --version` will display the versions of all the pre-commit hooks installed
* Display list versions of versions of pre-commit hooks installed when running `secureli --version`
* Added launch.json setting file to debug in vscode
* All existing unit tests are passing
> feat: show versions of configured hooks for repo

- .github/workflows/build_and_test.yml
secureli-420
This PR will fix issues with BATS cache being installed in file area requiring root permission
* Update BATS installation file path
* No unit testing
> fix: set BATS custom paths

- .vscode/launch.json
- poetry.lock
- pyproject.toml
- secureli/repositories/repo_files.py
- tests/repositories/test_repo_files_repository.py
[secureli-374](https://github.com/slalombuild/secureli/issues/374)
Excludes binary files from scans.
* Added logic to skip binary files from scans
* Updated launch.json configs to avoid deprecated settings
* All existing tests passing, some updating required
* Added unit tests to test detection of binary files to be excluded
> feat: secureli 374 exclude binary files from secrets scans

- secureli/resources/files/pre-commit/lint/kotlin-pre-commit.yaml
secureli-392
Add linting support for Kotlin
* Implemented `ktlint` in addition to `detekt` for Kotlin repos
* All existing unit tests are passing
> feat: #392 kotlin language linter support

- secureli/actions/action.py
- secureli/modules/language_analyzer/language_support.py
- secureli/modules/shared/models/language.py
- tests/modules/language_analyzer/test_language_support.py
secureli-454
Audit of language analyzer for code bloat and quality
* Resulting changes from audit of language analyzer for code bloat and quality.
* All existing tests are passing.
> feat: code audit for bloat and quality in language analyzer

- secureli/actions/action.py
- secureli/modules/language_analyzer/language_support.py
- secureli/modules/shared/abstractions/pre_commit.py
- tests/actions/test_action.py
- tests/end-to-end/testinstallnewhooks.bats
- tests/end-to-end/testpreservehooks.bats
- tests/modules/language_analyzer/test_language_support.py
- tests/modules/shared/abstractions/test_pre_commit.py
secureli-XXX
in a final check on recent work, I noticed that init was failing if there was no .pre-commit-config.yaml. This should fix that issue, maintain new functionality for copying existing yaml settings, and update tests.
* Updated action, language_support, and pre_commit to account for a lack of a .pre-commit-config.yaml by creating blank one if it doesn't exist. If it does exist and isn't where we want it, we move it.
* all tests pass
* in a dummy repo, run secureli init _with_ a .pre-commit-config.yaml in the root directory
* in a dummy repo, run secureli init _without_ a .pre-commit-config.yaml in the root directory
> Feat: secureli 372 fix init when no pre-commit-config exists

- .secureli/.pre-commit-config.yaml
- secureli/repositories/repo_settings.py
secureli-512
Secureli init failed/errors out on initialization of repo with C# language.  This PR resolves that issue.
* Made 'rev' property on pre-commit repo setting optional.
* All existing unit tests passing
> feat: bugfix for error on init of C# repos

- .github/workflows/publish.yml
- .github/workflows/smoke_testing.yml
secureli-437
Changes the name of the integration test workflow to smoke test. 
According to [the issue raised on stack overflow here](https://stackoverflow.com/questions/57927115/delete-a-workflow-from-github-actions#57927776), and [the github documentation here](https://docs.github.com/en/actions/managing-workflow-runs/deleting-a-workflow-run), the old integration test workflow history should remain. Workflow runs must be deleted manually, and renaming the files should create a new workflow.
If the Integration Test workflow is still active after this PR is merged, it should be disabled. [How to disable a workflow](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow#disabling-a-workflow)
* Rename .github/workflows/integration_testing.yml to …
> chore: change workflow name

- poetry.lock
- pyproject.toml
secureli-526
Add the GitPython package to our list of dependencies so that Poetry adds it on install.
* add gitpython to pyproject.toml
* regenerated lock file with updated gitpython version
* poetry install also made some updates to the extra optional dependencies in the lock file
Ran Secureli init after a clean install, it passed
Ran Poe Tests
> fix: add GitPython to dependencies list

- .secureli/.pre-commit-config.yaml
- secureli/actions/action.py
- secureli/actions/initializer.py
- secureli/actions/scan.py
- secureli/modules/shared/models/install.py
- tests/actions/test_action.py
secureli-537
Fixed bug that says "seCureLI is installed and up-to-date for the following language(s)", even though seCureLI is not initialized completely in that branch. This is an edge case where seCureLI has been installed on one branch, but not on the other branch in the same directory due to seCureLI artifacts that are git ignored.
* Added messaging and stop of secureli process when this edge case occurs.
* Updated detect-secret hook version
* Added required tests
* All existing tests are passing
> feat: Prompted to ReInstall When Running on Branch

- secureli/actions/action.py
secureli-494
* creates `_update_config` helper function to be used in `verify_install`
*  creates `_pre_install_checks` helper function to be used in `_install_secureli`
* no additional tests, existing tests pass
> feat: Feature/secureli 494 refactor action.py

- README.md
- secureli/container.py
- secureli/modules/pii_scanner/pii_scanner.py
- secureli/modules/shared/models/repository.py
- secureli/settings.py
- tests/modules/pii_scanner/test_pii_scanner_service.py
secureli-558
I'm on a Go project, and need the ability to add additional file extensions, as the default set doesn't include them. Within the project, go.mod and go.sum were including entries that appeared to be phone numbers. There was no way to configure PII Scanner to ignore these files, as any practical contents of these files would not be PII.
Rather than simply add them to the growing set of excluded extensions, I thought I would make the set configurable.
As the set contains language-agnostic files, I also elected NOT to include the go-specific files in that set.
A good follow-up work would be to also lay out, and selectively activate, additional extensions to ignore based on the languages configured in the repo.
* `pii_scanner` is added to the .secureli-config.yaml file structure …
> feat: Ignored file extensions can now be configured in the PII scanner

- README.md
secureli-540
This ticket was about a problem with configuring the pre-commit library. I determined that the issue was due to misconfiguration by the user, and the solution we settled on was to add documentation about how to specify args in the pre-commit library's configuration file.
Additionally, I updated headings throughout the file. Previously there were multiple H1s, and the License section was nested underneath the Configuration section. I've updated it so that there is only a single H1 heading--the title of the document--and the License section is now a sibling of configuration instead of a child.
* Updated headings throughout the file
* Added information and links for the pre-commit library
* Added information about a quirk of how pre-commit handles parameters that take arguments …
> docs: secureli 540 update documentation

- CONTRIBUTING.md
secureli-XXX
This change adds the setup steps for contributors using windows machines
Added windows developer configuration information to contributing.md
*
> docs: added windows set up documentation

- .secureli.yaml
- README.md
- secureli/actions/action.py
- secureli/actions/initializer.py
- secureli/main.py
- secureli/modules/language_analyzer/language_support.py
- tests/modules/language_analyzer/test_language_support.py
secureli-570
An existing precommit config file will be overwritten when running `secureli init`.
I've added a flag to the init action to prevent overwriting the config-- `secureli init --preserve-precommit-config'
* Added `--preserve-precommit-config` parameter to init action
* Added copy of existing test with the flag added
> fix: Precommit config overwritten on init
